

export const abbreviations: { abbr: string; full: string }[] = [
  { abbr: 'AI', full: 'Aide Inspiratoire' },
  { abbr: 'APV', full: 'Asynchronie Patient-Ventilateur' },
  { abbr: 'ATS', full: 'American Thoracic Society' },
  { abbr: 'AVAPS', full: 'Average Volume-Assured Pressure Support (Pression de support à volume garanti)' },
  { abbr: 'BNP', full: 'Peptide Natriurétique de type B' },
  { abbr: 'BPCO', full: 'Bronchopneumopathie Chronique Obstructive' },
  { abbr: 'CNVS', full: 'Support ventilatoire non invasif continu' },
  { abbr: 'CO₂', full: 'Dioxyde de Carbone' },
  { abbr: 'CPAP', full: 'Continuous Positive Airway Pressure (Pression Positive Continue)' },
  { abbr: 'CRF', full: 'Capacité Résiduelle Fonctionnelle' },
  { abbr: 'DMD', full: 'Dystrophie Musculaire de Duchenne' },
  { abbr: 'DTF', full: 'Diaphragm Thickening Fraction (Fraction de Raccourcissement Diaphragmatique)' },
  { abbr: 'ECG', full: 'Électrocardiogramme' },
  { abbr: 'EPAP', full: 'Expiratory Positive Airway Pressure (équivalent de la PEP)' },
  { abbr: 'ERS', full: 'European Respiratory Society' },
  { abbr: 'EtCO₂', full: 'End-tidal CO₂ (Capnographie)' },
  { abbr: 'FC', full: 'Fréquence Cardiaque' },
  { abbr: 'FEVG', full: "Fraction d'Éjection du Ventricule Gauche" },
  { abbr: 'FiO₂', full: 'Fraction inspirée en oxygène' },
  { abbr: 'FR', full: 'Fréquence Respiratoire' },
  { abbr: 'FVC', full: 'Capacité Vitale Forcée' },
  { abbr: 'GAVO2', full: 'Groupe assistance ventilatoire & oxygène' },
  { abbr: 'GCS', full: 'Glasgow Coma Scale (Score de Glasgow)' },
  { abbr: 'GDS', full: 'Gaz du Sang' },
  { abbr: 'HACOR', full: 'Score prédictif (Heart rate, Acidosis, Consciousness, Oxygenation, Respiratory rate)' },
  { abbr: 'HDU', full: 'High Dependency Unit (Unité de Surveillance Continue)' },
  { abbr: 'HFCWO', full: 'Oscillation de la Paroi Thoracique à Haute Fréquence' },
  { abbr: 'IAH', full: "Index d'Apnées/Hypopnées" },
  { abbr: 'ICU', full: 'Intensive Care Unit (Unité de Soins Intensifs)' },
  { abbr: 'IEC', full: "Inhibiteur de l'Enzyme de Conversion" },
  { abbr: 'IMC', full: 'Indice de Masse Corporelle' },
  { abbr: 'IPAP', full: 'Inspiratory Positive Airway Pressure (PEP + AI)' },
  { abbr: 'IRA', full: 'Insuffisance Respiratoire Aiguë' },
  { abbr: 'IRA-H', full: 'Insuffisance Respiratoire Aiguë Hypoxémique' },
  { abbr: 'IRAH', full: 'Insuffisance Respiratoire Aiguë Hypercapnique' },
  { abbr: 'IRC', full: 'Insuffisance Respiratoire Chronique' },
  { abbr: 'iVAPS', full: 'intelligent Volume-Assured Pressure Support' },
  { abbr: 'LUS', full: "Lung Ultrasound Score (Score d'échographie pulmonaire)" },
  { abbr: 'MAC', full: 'Toux Assistée Mécaniquement' },
  { abbr: 'MI-E', full: 'In-Exsufflateur Mécanique' },
  { abbr: 'MNM', full: 'Maladie Neuromusculaire' },
  { abbr: 'NHF', full: 'High-Flow Nasal Cannula (Oxygénothérapie Nasale à Haut Débit)' },
  { abbr: 'NIOV', full: 'Non-Invasive Open Ventilation' },
  { abbr: 'NPV', full: 'Negative Pressure Ventilation (Ventilation à Pression Négative)' },
  { abbr: 'OAP', full: 'Œdème Aigu du Poumon' },
  { abbr: 'OHD', full: 'Oxygénothérapie à Haut Débit (équivalent à NHF)' },
  { abbr: 'O₂', full: 'Oxygène' },
  { abbr: 'P/F', full: 'Rapport PaO₂/FiO₂' },
  { abbr: 'PA', full: 'Pression Artérielle' },
  { abbr: 'PaCO₂', full: 'Pression partielle artérielle en dioxyde de carbone' },
  { abbr: 'PaO₂', full: 'Pression partielle artérielle en oxygène' },
  { abbr: 'PAP', full: 'Pression Positive des Voies Aériennes' },
  { abbr: 'PAS', full: 'Pression Artérielle Systolique' },
  { abbr: 'PCF', full: 'Peak Cough Flow (Débit de Toux de Pointe)' },
  { abbr: 'PEG', full: 'Gastrostomie Endoscopique Percutanée' },
  { abbr: 'PEM', full: 'Pression Expiratoire Maximale' },
  { abbr: 'PEEP', full: 'Pression Expiratoire Positive' },
  { abbr: 'PETCO₂', full: "CO₂ de fin d'expiration" },
  { abbr: 'PIM', full: 'Pression Inspiratoire Maximale' },
  { abbr: 'PNI', full: 'Pression Non Invasive' },
  { abbr: 'P-SILI', full: 'Patient-Self Inflicted Lung Injury (Lésion Pulmonaire Auto-Infligée)' },
  { abbr: 'PtcCO₂', full: 'Pression transcutanée en CO₂' },
  { abbr: 'ROX', full: 'Index prédictif (Ratio of oxygen saturation / FiO₂) / Respiratory rate' },
  { abbr: 'RSBI', full: 'Rapid Shallow Breathing Index' },
  { abbr: 'SAOS', full: "Syndrome d'Apnées Obstructives du Sommeil" },
  { abbr: 'SLA', full: 'Sclérose Latérale Amyotrophique' },
  { abbr: 'SNIP', full: 'Pression Inspiratoire Nasale par Reniflement' },
  { abbr: 'SOH', full: 'Syndrome Obésité-Hypoventilation' },
  { abbr: 'SpO₂', full: 'Saturation pulsée en oxygène' },
  { abbr: 'SPLF', full: 'Société de Pneumologie de Langue Française' },
  { abbr: 'Ti', full: 'Temps Inspiratoire' },
  { abbr: 'USI', full: 'Unité de Soins Intensifs' },
  { abbr: 'VAPS', full: 'Volume-Assured Pressure Support' },
  { abbr: 'VC', full: 'Capacité Vitale' },
  { abbr: 'VG', full: 'Ventricule Gauche' },
  { abbr: 'VMI', full: 'Ventilation Mécanique Invasive' },
  { abbr: 'VNI', full: 'Ventilation Non Invasive' },
  { abbr: 'VS-AI-PEP', full: 'Ventilation Spontanée avec Aide Inspiratoire et PEP' },
  { abbr: 'Vt', full: 'Volume courant' },
  { abbr: 'VTe', full: 'Volume courant expiré' }
];
